// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  conditionId: __t.u64(),
  checkId: __t.u64(),
  sourceType: __t.string(),
  title: __t.string(),
  url: __t.option(__t.string()),
  snippet: __t.string(),
  authorOrSource: __t.option(__t.string()),
  sourcePublishedAt: __t.option(__t.string()),
  relevanceScore: __t.option(__t.f32()),
};
