// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conditionId: __t.u64().name("condition_id"),
  checkId: __t.u64().name("check_id"),
  sourceType: __t.string().name("source_type"),
  title: __t.string(),
  url: __t.option(__t.string()),
  snippet: __t.string(),
  authorOrSource: __t.option(__t.string()).name("author_or_source"),
  sourcePublishedAt: __t.option(__t.string()).name("source_published_at"),
  relevanceScore: __t.option(__t.f32()).name("relevance_score"),
  createdAt: __t.timestamp().name("created_at"),
});
