// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Condition = __t.object("Condition", {
  id: __t.u64(),
  owner: __t.identity(),
  prompt: __t.string(),
  status: __t.string(),
  finalResult: __t.option(__t.bool()),
  settlementStatus: __t.string(),
  settlementSignature: __t.option(__t.string()),
  dealId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Condition = __Infer<typeof Condition>;

export const Evidence = __t.object("Evidence", {
  id: __t.u64(),
  conditionId: __t.u64(),
  checkId: __t.u64(),
  sourceType: __t.string(),
  title: __t.string(),
  url: __t.option(__t.string()),
  snippet: __t.string(),
  authorOrSource: __t.option(__t.string()),
  sourcePublishedAt: __t.option(__t.string()),
  relevanceScore: __t.option(__t.f32()),
  createdAt: __t.timestamp(),
});
export type Evidence = __Infer<typeof Evidence>;

export const UploadedDocument = __t.object("UploadedDocument", {
  id: __t.u64(),
  conditionId: __t.u64(),
  fileName: __t.string(),
  mimeType: __t.string(),
  byteCount: __t.u64(),
  contentHash: __t.string(),
  storageReference: __t.string(),
  extractionStatus: __t.string(),
  textExcerpt: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UploadedDocument = __Infer<typeof UploadedDocument>;

export const VerificationCheck = __t.object("VerificationCheck", {
  id: __t.u64(),
  conditionId: __t.u64(),
  sequence: __t.u32(),
  kind: __t.string(),
  label: __t.string(),
  instruction: __t.string(),
  status: __t.string(),
  passed: __t.option(__t.bool()),
  summary: __t.option(__t.string()),
  evidenceCount: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VerificationCheck = __Infer<typeof VerificationCheck>;

