// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conditionId: __t.u64().name("condition_id"),
  fileName: __t.string().name("file_name"),
  mimeType: __t.string().name("mime_type"),
  byteCount: __t.u64().name("byte_count"),
  contentHash: __t.string().name("content_hash"),
  storageReference: __t.string().name("storage_reference"),
  extractionStatus: __t.string().name("extraction_status"),
  textExcerpt: __t.option(__t.string()).name("text_excerpt"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
