// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conditionId: __t.u64().name("condition_id"),
  sequence: __t.u32(),
  kind: __t.string(),
  label: __t.string(),
  instruction: __t.string(),
  status: __t.string(),
  passed: __t.option(__t.bool()),
  summary: __t.option(__t.string()),
  evidenceCount: __t.u32().name("evidence_count"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
