// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddEvidenceReducer from "../add_evidence_reducer";
import AddVerificationCheckReducer from "../add_verification_check_reducer";
import AssociateDemoDealReducer from "../associate_demo_deal_reducer";
import CompleteCheckReducer from "../complete_check_reducer";
import CreateConditionReducer from "../create_condition_reducer";
import EnableConditionReducer from "../enable_condition_reducer";
import RecordSettlementStatusReducer from "../record_settlement_status_reducer";
import RecordUploadedDocumentReducer from "../record_uploaded_document_reducer";
import ResolveConditionReducer from "../resolve_condition_reducer";
import SetCheckErrorReducer from "../set_check_error_reducer";
import SetCheckRunningReducer from "../set_check_running_reducer";
import SetConditionStatusReducer from "../set_condition_status_reducer";
import SetDocumentExtractionStatusReducer from "../set_document_extraction_status_reducer";
import TriggerConditionReducer from "../trigger_condition_reducer";
import UpdateConditionPromptReducer from "../update_condition_prompt_reducer";
import UpdateVerificationCheckReducer from "../update_verification_check_reducer";

export type AddEvidenceParams = __Infer<typeof AddEvidenceReducer>;
export type AddVerificationCheckParams = __Infer<typeof AddVerificationCheckReducer>;
export type AssociateDemoDealParams = __Infer<typeof AssociateDemoDealReducer>;
export type CompleteCheckParams = __Infer<typeof CompleteCheckReducer>;
export type CreateConditionParams = __Infer<typeof CreateConditionReducer>;
export type EnableConditionParams = __Infer<typeof EnableConditionReducer>;
export type RecordSettlementStatusParams = __Infer<typeof RecordSettlementStatusReducer>;
export type RecordUploadedDocumentParams = __Infer<typeof RecordUploadedDocumentReducer>;
export type ResolveConditionParams = __Infer<typeof ResolveConditionReducer>;
export type SetCheckErrorParams = __Infer<typeof SetCheckErrorReducer>;
export type SetCheckRunningParams = __Infer<typeof SetCheckRunningReducer>;
export type SetConditionStatusParams = __Infer<typeof SetConditionStatusReducer>;
export type SetDocumentExtractionStatusParams = __Infer<typeof SetDocumentExtractionStatusReducer>;
export type TriggerConditionParams = __Infer<typeof TriggerConditionReducer>;
export type UpdateConditionPromptParams = __Infer<typeof UpdateConditionPromptReducer>;
export type UpdateVerificationCheckParams = __Infer<typeof UpdateVerificationCheckReducer>;

