"use client";
import { useState } from "react";
const conditionId = "housing_fifty_percent_done";
const explorer = (sig?: string) => sig ? `https://explorer.solana.com/tx/${sig}?cluster=devnet` : undefined;
async function api(url: string, init?: RequestInit) { const r = await fetch(url, init); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Request failed"); return data; }
export default function Home() {
  const [deal, setDeal] = useState<any>(); const [platform, setPlatform] = useState(false); const [notice, setNotice] = useState("Ready. Create and fund a deal first; then the other buttons become available. This demo uses devnet SOL only."); const [busy, setBusy] = useState(false);
  const run = async (work: () => Promise<void>) => { setBusy(true); try { await work(); } catch (e) { setNotice(`Error: ${e instanceof Error ? e.message : "Unknown error"}`); } finally { setBusy(false); } };
  const refresh = async () => { if (!deal) return; const d = await api(`/api/deal/${deal.dealId}`); setDeal((current: any) => ({ ...(current ?? deal), ...d })); setNotice("On-chain deal state refreshed."); };
  const setResult = (result: boolean) => run(async () => { await api("/api/platform/result", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ result, dealId: deal?.dealId, conditionId }) }); setPlatform(result); setNotice(`Fake platform result set to ${result}. Nothing has been sent on-chain yet.`); });
  return <main className="mx-auto max-w-3xl space-y-5 p-8"><h1 className="text-3xl font-bold">Conditional Escrow — Devnet MVP</h1><p className="text-slate-400">platform result → centralized verifier → Solana program → native SOL release</p>
    <section className="card grid grid-cols-1 gap-3 sm:grid-cols-2"><div><div className="label">Deal ID</div>{deal?.dealId ?? "Not created"}</div><div><div className="label">Condition ID</div>{conditionId}</div><div><div className="label">Recipient address</div><code className="break-all text-xs">{deal?.recipient ?? "Created server-side"}</code></div><div><div className="label">Payment amount</div>0.1 SOL</div><div><div className="label">Solana network</div>Devnet only</div><div><div className="label">Platform result (not on-chain)</div>{String(platform)}</div></section>
    <section className="flex flex-wrap gap-3"><button disabled={busy} onClick={() => run(async () => { const created = await api("/api/deal/create", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ conditionId, amountSol: 0.1 }) }); const state = await api(`/api/deal/${created.dealId}`); setDeal({ ...created, ...state }); setPlatform(false); setNotice("Deal created and funded. One devnet transaction created the deal and deposited 0.1 SOL into escrow."); })}>Create and Fund Deal</button><button disabled={busy || !deal} onClick={() => setResult(true)}>Set Platform Result: TRUE</button><button disabled={busy || !deal} onClick={() => setResult(false)}>Set Platform Result: FALSE</button><button disabled={busy || !deal} onClick={() => run(async () => { const r = await api("/api/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ dealId: deal.dealId, conditionId }) }); const state = await api(`/api/deal/${deal.dealId}`); setDeal((current: any) => ({ ...(current ?? deal), ...state, verifierSignature: r.transactionSignature })); setNotice(`Verifier read ${r.result} from the fake platform and submitted it on-chain.`); })}>Run Verification</button><button disabled={busy || !deal} onClick={() => run(async () => { const r = await api("/api/deal/release", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ dealId: deal.dealId }) }); const state = await api(`/api/deal/${deal.dealId}`); setDeal((current: any) => ({ ...(current ?? deal), ...state, releaseSignature: r.signature, recipientBalanceBefore: r.recipientBalanceBefore, recipientBalanceAfter: r.recipientBalanceAfter })); setNotice("Payment released on-chain."); })}>Release Payment</button><button disabled={busy || !deal} onClick={() => run(refresh)}>Refresh On-Chain State</button></section>
    <section className="card"><div className="label">Status</div><p>{notice}</p>{deal && <div className="mt-4 space-y-1 text-sm"><div>Escrow balance: {deal.escrowBalance === undefined ? "—" : `${deal.escrowBalance / 1e9} SOL`}</div><div>Condition result on-chain: {deal.hasResult ? String(deal.conditionResult) : "not submitted"}</div><div>Funded: {String(deal.funded)} · Released: {String(deal.released)}</div><div>Recipient balance: {deal.recipientBalance === undefined ? "—" : `${deal.recipientBalance / 1e9} SOL`}</div>{deal.recipientBalanceBefore !== undefined && <div>Recipient balance before release: {deal.recipientBalanceBefore / 1e9} SOL</div>}{deal.recipientBalanceAfter !== undefined && <div>Recipient balance after release: {deal.recipientBalanceAfter / 1e9} SOL</div>}{deal.createSignature && <div>Create + fund transaction: <a href={explorer(deal.createSignature)} target="_blank">View on Devnet Explorer</a></div>}{deal.verifierSignature && <div>Verifier transaction: <a href={explorer(deal.verifierSignature)} target="_blank">View on Devnet Explorer</a></div>}{deal.releaseSignature && <div>Release transaction: <a href={explorer(deal.releaseSignature)} target="_blank">View on Devnet Explorer</a></div>}</div>}</section>
  </main>;
}
